apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    name: iisviper-web
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iisviper-web-deployment
  labels:
    app: iisviper-web-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: iisviper-web
    spec:
      containers:
      - name: iisviper-web-cntnr
        image: rpmdevimages.azurecr.io/iisviperweb:v0
        ports:
        - containerPort: 80
          name: iisviper-web
