apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    name: iisviper
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iisviper-deployment
  labels:
    app: iisviper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iisviper
  template:
    metadata:
      labels:
        app: iisviper
    spec:
      containers:
      - name: iisviper
        image: rpmdevimages.azurecr.io/iisviperweb:v0
        ports:
        - containerPort: 80
